cuda: True
dry_run: False
dataset_name: ''
semi_supervised: False
seed: -1
verbose: True

loggers:
    logdir: './logs'
    log_every: 10
    log_grads_norm: 2

    tqdm:
        ncols: 120
        dynamic_ncols: False
        leave: False
        disable: False

   # neptune:
   #      project_name: 'USERNAME/test'
   #      experiment_name: 'test'
   #      offline_mode: False

    # sacred:
    #     use_sacred: False
    #     mongodb_disable: False
    #     mongodb_url: '127.0.0.1'
    #     mongodb_port: 27017
    #     mongodb_name: ''
    #     mongodb_prefix: ''

optimizer:
    name: 'adam'
    params:
        lr: 0.001
    regularizers:
        weight_decay: 0.0

