cuda: True
dry_run: False
seed: -1
verbose: True
restore_path: ''
mode: 'train'

data:
    datadir: '${env:YAPT_DATADIR}'  # all datasets are stored in this path (prefix)
    dataset_path: ''                # where the experiment dataset is stored
    dataset_name: ''                # just a description of the dataset, could also be the yml in dataset_path with dataset defaults
    semi_supervised: False
    alternated_update: True
    num_workers: 4
    pin_memory: True

num_batches_train:
num_batches_val:
num_batches_test:

accum_batches: 1
grads_norm_clip:
    max_norm: -1
    norm_type: 2

debug:
    save_inputs: False

loggers:
    images:
    debug: False
    logdir: '${env:YAPT_LOGDIR}'
    checkpoints_format: 'epoch_{}.pt'
    keep_only_last_checkpoint: True
    keep_topk_checkpoints: 5

    log_every: 10
    validate_every: 1
    save_every: 1

    log_grads_norm: 2
    tensorboard: False

    tqdm:
        ncols: 120
        dynamic_ncols: False
        leave: False
        disable: False

    neptune:
        exp_id: -1
        offline_mode: False
        project_name: 'USERNAME/test'
        upload_source_files: ['*.py', '*.yml', '*.yaml', '.git/*', 'docker/*']
        tags: []

optimizer:
    name: 'adam'
    params:
        lr: 0.001
    regularizers:
        weight_decay: 0.0

    # scheduler:
    #     name: 'cosine'
    #     params:
    #         eta_min: 1e-5  # min_lr
    #         T_max: ${max_epochs}
