cuda: True
dry_run: False
dataset_name: ''
semi_supervised: False
alternated_update: True
seed: -1
verbose: True
restore_path: ''
mode: 'train'
validate_every: 1
save_every: 1

loggers:
    checkpoints_format: 'epoch_{}.pt'
    logdir: './logs'
    log_every: 10
    log_grads_norm: 2

    tqdm:
        ncols: 120
        dynamic_ncols: False
        leave: False
        disable: False

    neptune:
        exp_id: -1
        offline_mode: False
        project_name: 'USERNAME/test'
        tags: []

    # sacred:
    #     use_sacred: False
    #     mongodb_disable: False
    #     mongodb_url: '127.0.0.1'
    #     mongodb_port: 27017
    #     mongodb_name: ''
    #     mongodb_prefix: ''

optimizer:
    name: 'adam'
    params:
        lr: 0.001
    regularizers:
        weight_decay: 0.0

    # scheduler:
    #     name: 'cosine'
    #     params:
    #         eta_min: 1e-5  # min_lr
    #         T_max: ${max_epochs}
