trainer:
    dry_run: False
    dataset_name: ''
    semi_supervised: False
    cuda: True
    seed: -1
    verbose: True

loggers:
    logdir: './logs'
    log_every: 10

sacred:
    use_sacred: False
    mongodb_disable: False
    mongodb_url: '127.0.0.1'
    mongodb_port: 27017
    mongodb_name: ''
    mongodb_prefix: ''

tqdm:
    ncols: 80
    dynamic_ncols: False
    leave: False
    disable: False

