
cudnn:
    benchmark: False
    deterministic: True

dataset_name: 'mnist'
datadir: './datasets'
start_epoch: 0
restart_path: ''
use_new_dir: False
reload_model: ''
num_workers: 4

only_test: False
exp_name: 'mnist_example'
device: 'cuda'
cuda: true
seed: 0

# Optimizer
max_epochs: 10
batch_size: 100

# Network
net_params:
    hidden_dim: 100
    drop_prob: 0.5
    out_dim: 10

optimizer:
    name: 'adam'
    params:
        lr: 0.001
    regularizers:
        weight_decay: 0.0

# Early stopping
early_stopping:
    patience: 10
    dataset: 'validation'
    metric: 'val_acc'

input_dims: [1, 28, 28]

