loggers:
    tqdm:
        disable: False
        ncols: 80

    neptune:
        project_name: '${env:NEPTUNE_USER}/mnist-example'
        offline_mode: False

cudnn:
    benchmark: False
    deterministic: True

data:
    dataset_name: 'mnist'
    num_workers: 1
    pin_memory: True

start_epoch: 0
only_test: False
exp_name: 'mnist_example'

# Optimizer
max_epochs: 10
batch_size: 100

# Network
net_params:
    hidden_dim: 100
    drop_prob: 0.5
    out_dim: 10

optimizer:
    name: 'adam'
    params:
        lr: 0.001
    regularizers:
        weight_decay: 0.0

# Early stopping
early_stopping:
    patience: 10
    dataset: 'validation'
    metric: 'validation/y_acc'
    mode: 'max'

input_dims: [1, 28, 28]

